version: '3'
services:
  web:
    image: ghcr.io/sammcb/jekyll
    ports:
      - 4000:4000
    volumes:
      - .:/sammcb
    container_name: web
    working_dir: /sammcb
    tty: true
    stdin_open: true
