name: Build and deploy

on: [pull_request, workflow_dispatch]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build site files
      run: |
        ./do.sh init
        mkdir _site
        ./do.sh build
    - name: Push to pages branch
      uses: Sammcb/push-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        paths: _site/*
