name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: ruby:3.1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Build site files
      run: |
        ./do.sh init
        ./do.sh build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: _site/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
