name: Release
on:
  release:
    types: [created]
permissions: {}
concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      security-events: write
  release:
    runs-on: ubuntu-24.04-arm
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      id-token: write
      pages: write
    needs: ci
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        merge-multiple: true
        path: artifacts
    - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: artifacts
    - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
      id: deployment
